spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bill4self?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: xuebushen
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis-plus:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.bill4self.system.entity

logging:
  level:
    com.example.bill4self.mapper: trace
  config: classpath:log4j2.yml

server:
  port: 8081
  servlet:
    context-path: /

knife4j:
  basic:
    username: mp
    password: 123456
    enable: true #开启认证
  production: false #默认是false ,屏蔽所有Swagger的相关资源
  enable: true #是否开启swagger